app = "flowise-me"
primary_region = "ewr"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1024

[env]
  FLOWISE_USERNAME = "admin"
  FLOWISE_PASSWORD = "3Tomazeli9$"
  BLOB_STORAGE_PATH = "/root/.flowise/data"
  DATABASE_PATH    = "/root/.flowise/flowise.db"
  SECRETKEY_PATH   = "/root/.flowise/data"
  APIKEY_PATH      = "/root/.flowise/data"

[[mounts]]
  source = "flowise_data"
  destination = "/root/.flowise"
